// Dados dos recursos. Edite, adicione ou remova itens. c = índice da categoria (0-9); lat/lng = null se não houver coordenadas.
const RECURSOS=[
 {
  "id": 1,
  "n": "Portal de Serviços e canais digitais da Prefeitura",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Portal oficial com serviços online e canais municipais.",
  "a": "Nova Friburgo, RJ",
  "h": "Atendimento geral: seg a sex, 09h às 17h",
  "t": "(22) 2525-9100",
  "l": "https://www.pmnf.rj.gov.br/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 2,
  "n": "Secretaria Municipal de Cultura",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Responsável pelas políticas culturais do município.",
  "a": "Rua Farinha Filho, 50, Centro",
  "h": "09h às 17h",
  "t": "gabinetecultura.pmnf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/7/cultura",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2818,
  "lng": -42.5332
 },
 {
  "id": 3,
  "n": "Secretaria Municipal de Educação",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Rede de educação e ações educacionais do município.",
  "a": "Av. Alberto Braune, 224, Centro",
  "h": "09h às 17h",
  "t": "gabinete@sme.novafriburgo.rj.gov.br",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/5/educacao",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2855,
  "lng": -42.5341
 },
 {
  "id": 4,
  "n": "Secretaria Municipal de Esportes e Lazer",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Ações municipais de esporte, lazer e atividades comunitárias.",
  "a": "Av. Alberto Braune, 225, Centro",
  "h": "09h às 17h",
  "t": "smel.pmnf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/9/esportes-e-lazer",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2858,
  "lng": -42.5343
 },
 {
  "id": 5,
  "n": "Secretaria de Serviços e Equipamentos Públicos",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Manutenção e serviços/equipamentos públicos municipais.",
  "a": "Av. Alberto Braune, 225, Centro",
  "h": "09h às 17h",
  "t": "ssppmnf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/15/servicos-e-equipamentos-publicos",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2858,
  "lng": -42.5343
 },
 {
  "id": 6,
  "n": "Proteção e Defesa Civil",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Órgão de proteção e Defesa Civil; canais de emergência.",
  "a": "Av. Alberto Braune, 223, antiga Rodoviária, Centro",
  "h": "09h às 17h; emergências 24h pelo 199",
  "t": "199 | (22) 2522-8182",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/17/protecao-e-defesa-civil",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2852,
  "lng": -42.534
 },
 {
  "id": 7,
  "n": "Secretaria de Agricultura e Desenvolvimento Rural",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Agricultura e desenvolvimento rural; informa o Serviço de Inspeção Municipal.",
  "a": "Av. Alberto Braune, 223, Centro",
  "h": "09h às 18h",
  "t": "sec.agricultura.nf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/13/agricultura-e-desenvolvimento-rural",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2852,
  "lng": -42.534
 },
 {
  "id": 8,
  "n": "Secretaria de Ambiente e Desenvolvimento Urbano Sustentável",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Ações e serviços de meio ambiente e desenvolvimento urbano sustentável.",
  "a": "Av. Alberto Braune, 225, Centro",
  "h": "09h às 17h",
  "t": "secretaria.smapmnf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/12/ambiente-e-desenvolvimento-urbano-sustentavel",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2858,
  "lng": -42.5343
 },
 {
  "id": 9,
  "n": "Secretaria de Desenvolvimento Social e Direitos Humanos",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Políticas de desenvolvimento social e direitos humanos.",
  "a": "Alameda Eduardo Guinle, 137, Parque São Clemente",
  "h": "09h às 17h",
  "t": "(22) 2522-1339 | smasnf@gmail.com",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/11/desenvolvimento-social-e-direitos-humanos",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2891,
  "lng": -42.5374
 },
 {
  "id": 10,
  "n": "Secretaria de Ciência, Tecnologia, Inovação e Desenv. Econômico",
  "c": 0,
  "d": "Sede",
  "b": "Centro",
  "desc": "Ciência, tecnologia, inovação, desenvolvimento econômico e qualificação.",
  "a": "Av. Alberto Braune, 223, 2º andar, Centro",
  "h": "09h às 17h",
  "t": "smctieps@sme.novafriburgo.rj.gov.br",
  "l": "https://www.pmnf.rj.gov.br/secretaria/view/6/ciencia-tecnologia-inovacao-e-desenvolvimento-economico",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2852,
  "lng": -42.534
 },
 {
  "id": 11,
  "n": "CEVEST — Formação Profissional para a Indústria do Vestuário",
  "c": 6,
  "d": "Sede",
  "b": "Centro",
  "desc": "Cursos gratuitos; pré-inscrição também presencial para quem não tem internet.",
  "a": "Av. Alberto Braune, 225, Centro",
  "h": "09h às 17h",
  "t": "(22) 2525-9145",
  "l": "https://cevest.pmnf.rj.gov.br/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2858,
  "lng": -42.5343
 },
 {
  "id": 12,
  "n": "Estação Cidadania (antiga Praça CEU)",
  "c": 3,
  "d": "Sede",
  "b": "Olaria",
  "desc": "Complexo comunitário com assistência social, esporte e cultura.",
  "a": "Via Expressa, Olaria",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/noticia/view/2311",
  "s": "Verificado",
  "o": "Horário só encontrado em fonte de 2022 — confirmar.",
  "dt": "22/09/2026",
  "lat": -22.3065,
  "lng": -42.5395
 },
 {
  "id": 13,
  "n": "Casa de Cultura e Cidadania Casarão do Lazareto",
  "c": 8,
  "d": "Sede",
  "b": "Duas Pedras",
  "desc": "Espaço cultural e comunitário inaugurado em maio de 2026.",
  "a": "Bairro Duas Pedras",
  "h": "",
  "t": "",
  "l": "https://pmnf.rj.gov.br/noticia/view/5328",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2615,
  "lng": -42.516
 },
 {
  "id": 14,
  "n": "Teatro Municipal Laercio Rangel Ventura",
  "c": 8,
  "d": "Sede",
  "b": "Centro",
  "desc": "Programação teatral e outras atividades artísticas.",
  "a": "Praça do Suspiro, Centro",
  "h": "",
  "t": "(22) 99810-8633 | teatromunicipalnovafriburgo@gmail.com",
  "l": "https://pmnf.rj.gov.br/noticia/view/5156",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2809,
  "lng": -42.5312
 },
 {
  "id": 15,
  "n": "Conecta Cultura (plataforma online)",
  "c": 8,
  "d": "",
  "b": "",
  "desc": "Cadastro de artistas, editais e projetos da Secretaria de Cultura.",
  "a": "Acesso digital",
  "h": "Online",
  "t": "",
  "l": "https://www.conectaculturanf.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 16,
  "n": "Pontos de Apoio da Defesa Civil (rede municipal)",
  "c": 0,
  "d": "",
  "b": "",
  "desc": "Pontos de atendimento em chuvas intensas; relação oficial em PDF/CSV.",
  "a": "Consultar relação oficial de pontos",
  "h": "Conforme alertas/sirenes",
  "t": "199 | (22) 2522-8182",
  "l": "https://www.pmnf.rj.gov.br/documento/view/52/defesa-civil-localizacao-dos-pontos-de-apoio",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 17,
  "n": "Pedra do Cão Sentado",
  "c": 4,
  "d": "",
  "b": "",
  "desc": "Ponto turístico oficial do município.",
  "a": "Parque de Alta Montanha de Nova Friburgo",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/turismo/view/1/pedra-do-cao-sentado",
  "s": "Verificado",
  "o": "Localização detalhada ainda a confirmar.",
  "dt": "22/09/2026",
  "lat": -22.2431,
  "lng": -42.5117,
  "img": "images/pedra-cao-sentado.jpg"
 },
 {
  "id": 18,
  "n": "Circuito Amparo",
  "c": 4,
  "d": "Amparo",
  "b": "",
  "desc": "Circuito turístico oficial do distrito de Amparo.",
  "a": "Distrito de Amparo",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/turismo/view/2/circuito-amparo",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 19,
  "n": "Turismo Rural",
  "c": 9,
  "d": "",
  "b": "",
  "desc": "Eixo de turismo rural listado pela Prefeitura.",
  "a": "Nova Friburgo, RJ",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/turismo/view/3/turismo-rural",
  "s": "Verificado",
  "o": "Sem localização única; detalhar por iniciativa.",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 20,
  "n": "Lumiar e São Pedro da Serra — turismo e ecoturismo",
  "c": 4,
  "d": "",
  "b": "",
  "desc": "Polos de gastronomia e turismo ecológico, com Mata Atlântica preservada.",
  "a": "Distritos de Lumiar e São Pedro da Serra",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/turismo/view/4/lumiar-e-sao-pedro-da-serra",
  "s": "Verificado",
  "o": "Abrange dois distritos.",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 21,
  "n": "Feira de Produtos Orgânicos ABIO",
  "c": 2,
  "d": "Sede",
  "b": "",
  "desc": "Feira recorrente de produtos orgânicos.",
  "a": "Rua das Rendas (Espaço ARP), Centro",
  "h": "Terças, 09h às 13h",
  "t": "",
  "l": "https://www.espacoarp.com.br/agenda-cultural/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2934,
  "lng": -42.533
 },
 {
  "id": 22,
  "n": "Exposição Colégio Anchieta 140 anos",
  "c": 8,
  "d": "Sede",
  "b": "Centro",
  "desc": "Exposição do Sesc RJ sobre a história do colégio. Entrada gratuita. Evento temporário.",
  "a": "Casarão Julius Arp, Av. Conselheiro Julius Arp, 80",
  "h": "Até 30/09/2026; qui a sáb 11h–20h, dom 11h–17h",
  "t": "",
  "l": "https://www.espacoarp.com.br/agenda-cultural/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2929,
  "lng": -42.5332
 },
 {
  "id": 23,
  "n": "Festa do Morango com Chocolate 2026",
  "c": 2,
  "d": "Sede",
  "b": "",
  "desc": "Evento gastronômico. Entrada paga.",
  "a": "Nova Friburgo Country Clube, Centro",
  "h": "08 a 12/10/2026",
  "t": "",
  "l": "https://www.festadomorangocomchocolate.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": -22.2895,
  "lng": -42.5398
 },
 {
  "id": 24,
  "n": "Agenda Cultural — Espaço ARP",
  "c": 8,
  "d": "",
  "b": "",
  "desc": "Agenda de eventos culturais e comunitários.",
  "a": "Acesso digital (sede: Av. Conselheiro Julius Arp, 80)",
  "h": "Online",
  "t": "(22) 2525-8300 | sac@arp.com.br",
  "l": "https://www.espacoarp.com.br/agenda-cultural/",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 25,
  "n": "Agenda de eventos — Nova Friburgo Agora",
  "c": 9,
  "d": "",
  "b": "",
  "desc": "Agenda online de eventos culturais e gastronômicos. Fonte complementar.",
  "a": "Acesso digital",
  "h": "Online",
  "t": "",
  "l": "https://novafriburgoagora.com.br/agenda",
  "s": "Verificado",
  "o": "",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 26,
  "n": "Casa do Artesão — Pavilhão das Artes",
  "c": 8,
  "d": "Sede",
  "b": "Cônego",
  "desc": "Espaço de artesanato e economia criativa.",
  "a": "Rua Romão Aguilera Campos, s/nº, Cônego",
  "h": "Informação de 2022 — confirmar",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/noticia/view/2540",
  "s": "Atualização necessária",
  "o": "Fonte de 2022; confirmar situação atual.",
  "dt": "22/09/2026",
  "lat": -22.3162,
  "lng": -42.5539
 },
 {
  "id": 27,
  "n": "Rede de Casas de Cultura e Cidadania",
  "c": 8,
  "d": "",
  "b": "",
  "desc": "Ações culturais e oficinas em Olaria, Conselheiro Paulino, Riograndina, Lazaretto e Praça CEU.",
  "a": "Vários territórios",
  "h": "",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/noticia/view/5281",
  "s": "Verificado",
  "o": "Endereços individuais a confirmar.",
  "dt": "22/09/2026",
  "lat": null,
  "lng": null
 },
 {
  "id": 28,
  "n": "Associação Pestalozzi de Nova Friburgo",
  "c": 7,
  "d": "Conselheiro Paulino",
  "b": "Conselheiro Paulino",
  "desc": "Entidade filantrópica que provê serviços gratuitos de habilitação, reabilitação e educação inclusiva para pessoas com deficiência.",
  "a": "Rua Dr. Sílvio Henrique Braune, 22 - Conselheiro Paulino",
  "h": "Segunda a sexta, 08h às 17h",
  "t": "(22) 2522-4228",
  "l": "http://www.pestalozzifriburgo.org.br/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2592,
  "lng": -42.5218
 },
 {
  "id": 29,
  "n": "Centro Social Nossa Senhora das Graças",
  "c": 1,
  "d": "Sede",
  "b": "Olaria",
  "desc": "Organização comunitária com projetos assistenciais e apoio a famílias, idosos e crianças em situação de vulnerabilidade.",
  "a": "Rua Vicente Sobrou, 25 - Olaria",
  "h": "Horários sob consulta",
  "t": "(22) 2522-8321",
  "l": "https://www.atados.com.br/ong/centro-social-nossa-senhora-das-gracas",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.3044,
  "lng": -42.5413
 },
 {
  "id": 30,
  "n": "Praça Primeiro de Maio",
  "c": 4,
  "d": "Sede",
  "b": "Olaria",
  "desc": "Principal ponto de encontro, convivência e lazer a céu aberto do bairro Olaria.",
  "a": "Praça Primeiro de Maio, Olaria",
  "h": "Espaço público aberto 24h",
  "t": "",
  "l": "https://avozdaserra.com.br/noticias/praca-1o-de-maio-e-parquinho-sao-examples-de-espaco-publico-bem-cuidado",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.307,
  "lng": -42.5405
 },
 {
  "id": 31,
  "n": "Ginásio Poliesportivo de Conselheiro Paulino",
  "c": 3,
  "d": "Conselheiro Paulino",
  "b": "Conselheiro Paulino",
  "desc": "Infraestrutura pública municipal recuperada, usada para esportes coletivos e lazer noturno.",
  "a": "Rua Clarindo Rosa da Silva, s/nº - Conselheiro Paulino",
  "h": "Conforme agenda esportiva local",
  "t": "",
  "l": "https://www.pmnf.rj.gov.br/noticia/view/816",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2533,
  "lng": -42.5185
 },
 {
  "id": 32,
  "n": "Feira do Cônego",
  "c": 2,
  "d": "Sede",
  "b": "Cônego",
  "desc": "Feira comunitária recorrente com alimentos e hortifrúti da agricultura familiar.",
  "a": "Praça Sant'Ana, Cônego",
  "h": "Sábados pela manhã",
  "t": "",
  "l": "http://instagram.com/feiraconego",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.3168,
  "lng": -42.5532
 },
 {
  "id": 33,
  "n": "Feira de Artesanato do Suspiro",
  "c": 8,
  "d": "Sede",
  "b": "Centro",
  "desc": "Feira de artesãos locais: vestuário, lembranças, artefatos manuais e gastronomia típica da serra.",
  "a": "Praça do Suspiro, Centro",
  "h": "Sábados, domingos e feriados, 09h às 18h",
  "t": "",
  "l": "https://descubranovafriburgo.com.br/pontos-turisticos/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2811,
  "lng": -42.531
 },
 {
  "id": 34,
  "n": "Polo de Moda Íntima - Olaria",
  "c": 9,
  "d": "Sede",
  "b": "Olaria",
  "desc": "Conjunto comercial e industrial reconhecido pela confecção e pelo desenvolvimento têxtil local.",
  "a": "Rua Júlio Antonio Thurler, Olaria",
  "h": "Horário comercial",
  "t": "",
  "l": "https://descubranovafriburgo.com.br/pontos-turisticos/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.309,
  "lng": -42.543
 },
 {
  "id": 35,
  "n": "Casa Suíça e Queijaria Escola",
  "c": 9,
  "d": "Campo do Coelho",
  "b": "Conquista",
  "desc": "Complexo cultural e memorial da colonização suíça, com queijos finos e chocolates artesanais.",
  "a": "Rodovia RJ-130, km 18 - Conquista",
  "h": "Terça a domingo, 09h às 17h",
  "t": "(22) 2543-2000",
  "l": "https://www.worldpackers.com/pt-BR/articles/o-que-fazer-em-nova-friburgo",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.241,
  "lng": -42.4345
 },
 {
  "id": 36,
  "n": "Sustentarp – Hub de Logística Reversa",
  "c": 5,
  "d": "Sede",
  "b": "Centro",
  "desc": "Ponto físico para educação ambiental e recebimento de óleo vegetal usado e metais.",
  "a": "Espaço ARP - Av. Conselheiro Julius Arp, 80, Centro",
  "h": "Segunda a sexta, 09h às 18h",
  "t": "(22) 2525-8300",
  "l": "https://www.espacoarp.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2929,
  "lng": -42.5332
 },
 {
  "id": 37,
  "n": "Ponto de Coleta Reciclotron (UFF)",
  "c": 5,
  "d": "Sede",
  "b": "Centro",
  "desc": "Contêiner para descarte e triagem de lixo eletroeletrônico, celulares, fios e periféricos.",
  "a": "Espaço ARP - Av. Conselheiro Julius Arp, 80, Centro",
  "h": "Segunda a sexta, 09h às 18h",
  "t": "",
  "l": "https://www.espacoarp.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2929,
  "lng": -42.5332
 },
 {
  "id": 38,
  "n": "Coletor de Gás Gear Tips",
  "c": 5,
  "d": "Sede",
  "b": "Centro",
  "desc": "Coleta e destinação segura de cilindros e cartuchos de gás vazios do montanhismo local.",
  "a": "Espaço ARP - Av. Conselheiro Julius Arp, 80, Centro",
  "h": "Segunda a sexta, 09h às 18h",
  "t": "",
  "l": "https://www.espacoarp.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2929,
  "lng": -42.5332
 },
 {
  "id": 39,
  "n": "Programa Curacycle",
  "c": 5,
  "d": "Sede",
  "b": "Centro",
  "desc": "Recepção de resíduos plásticos difíceis (tubos de pasta de dente, escovas) para reciclagem.",
  "a": "Espaço ARP - Av. Conselheiro Julius Arp, 80, Centro",
  "h": "Segunda a sexta, 09h às 18h",
  "t": "",
  "l": "https://www.espacoarp.com.br/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2929,
  "lng": -42.5332
 },
 {
  "id": 40,
  "n": "Sesc+ Educação (Turno Complementar)",
  "c": 6,
  "d": "Sede",
  "b": "Centro",
  "desc": "Reforço e educação integrada para crianças e jovens no contraturno e pré-vestibular comunitário gratuito.",
  "a": "Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Conforme turmas e editais",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 },
 {
  "id": 41,
  "n": "Espaço ACT Sesc (Fabricação Digital)",
  "c": 6,
  "d": "Sede",
  "b": "Centro",
  "desc": "Laboratório aberto com impressoras 3D e softwares livres para democratizar o acesso à tecnologia.",
  "a": "Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Agendamentos sob consulta",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 },
 {
  "id": 42,
  "n": "Colab Sesc (Empreendedorismo)",
  "c": 1,
  "d": "Sede",
  "b": "Centro",
  "desc": "Incubadora e mentoria coletiva, com cursos de gestão de negócios para mulheres das comunidades da serra.",
  "a": "Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Horários conforme calendário",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 },
 {
  "id": 43,
  "n": "Sesc + Vida (Idosos)",
  "c": 1,
  "d": "Sede",
  "b": "Centro",
  "desc": "Convivência para a terceira idade: ginástica adaptada, turismo social e rodas de conversa.",
  "a": "Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Dias úteis, turnos variados",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 },
 {
  "id": 44,
  "n": "Unidades Móveis Sesc (Saúde/Odonto)",
  "c": 1,
  "d": "Sede",
  "b": "Centro",
  "desc": "Atendimento itinerante com exames de rastreio (mamografia) e odontologia preventiva.",
  "a": "Itinerante / Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Conforme calendário municipal",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 },
 {
  "id": 45,
  "n": "Laboratório Criativo Sesc",
  "c": 8,
  "d": "Sede",
  "b": "Centro",
  "desc": "Ciclos formativos gratuitos em economia criativa para profissionais locais.",
  "a": "Sesc - Av. Pres. Costa e Silva, 231, Centro",
  "h": "Editais periódicos",
  "t": "(22) 2543-5000",
  "l": "https://www.sescrio.org.br/unidades/sesc-nova-friburgo/",
  "s": "Verificado",
  "o": "",
  "dt": "28/09/2026",
  "lat": -22.2872,
  "lng": -42.5298
 }
]
;
